<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$cartModel 	= $objectManager->get('\Magento\Checkout\Model\Cart');
	$helperData = $objectManager->create('Magehit\Customevent\Helper\Data');
?>

<?php if($helperData->getPresenterStatus()): ?>
<div class="custom-options" style="width: 50%;">
	<div class="block ">
		<div class="title">
			<strong><?php echo __('Referrals') ?></strong>
		</div>
		<?php 
			$quote = $cartModel->getQuote();
			//$quote->getPresenter();
		?>
		<div class="content">
			<form action="" method="post" id="presenter_custom_form">
			<div class="fieldset">
				<div class="field">
					<label><?php echo __('How did you hear about us?') ?><label>
					<div class="control">
						<?php $listPresenter =  $helperData->getListPresenter(); ?>
						<select id="presenter" name="custom[presenter]">
							<option value="" ><?php echo __('--Select--') ?></option>
							<?php foreach($listPresenter as $key=>$val): ?>
							<option value="<?php echo $key ?>" <?php echo @$quote->getPresenter() == $key ? 'selected': '';  ?>><?php echo $val ?></option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
				<div class="field ambassador-feild" <?php if($quote->getPresenter() != 3): ?>style="display:none;"<?php endif; ?>>
					<label><?php echo __('Enter name of the person who reffered you to us') ?></label>
					<div class="control">
						<input class="input-text" type="text" id="ambassador" name="custom[ambassador]" value="<?php echo @$quote->getAmbassador() ?>">
					</div>
				</div>
				<script type="text/javascript">
					require([
						'jquery'
					], function ($) {
						$('#presenter').change(function(){
							if(jQuery(this).val() == 3){
								jQuery('.ambassador-feild').show();
							}else{
								jQuery('.ambassador-feild').hide();
							}
						});
						
						$('#presenter,.ambassador-feild input').change(function(){
							$.ajax({
								url: "<?php echo $this->getUrl('customevent/index/savequote'); ?>",
								type: 'POST',
								dataType: 'json',
								data: $('#presenter_custom_form').serialize(),
								success: function(result){
									
								}
							});
						});
					});
				</script>
			</div>
			</form>
		</div>
	</div>
</div>
<br/>
<br/>
<?php endif; ?>