<?php 

$isVideoSingle = (!$block->canDisplay('title') && !$block->canDisplay('description') && !$block->canDisplay('meta'));
?>
<section class="mxYouTubeR mxYouTubeR_channel mxYouTubeR_theme_<?php echo $block->getData('theme');?>">
	<div class="mxyt-channel-head">
    	<div class="mxyt-channel-head-cover" style="background-image: url('<?php echo $block->channel->brandingSettings->image->bannerImageUrl; ?>');">
        	<div class="mxyt-channel-logo"><img src="<?php echo $block->channel->snippet->thumbnails->medium->url;?>" alt="<?php echo $block->channel->snippet->title;?>" /></div>
            <div class="mxyt-channel-info">
                <span><?php echo __('Videos: %1',$block->channel->statistics->videoCount); ?></span>
                <span><?php echo __('Views: %1',$block->channel->statistics->viewCount); ?></span>
                <span><?php echo __('Subscribers: %1',$block->channel->statistics->subscriberCount); ?></span>
            </div>
        </div>
        <div class="mxyt-channel-title">
			<?php echo $block->channel->snippet->title;?>
			<div class="mxyt-channel-subscr-btn">
				<script src="https://apis.google.com/js/platform.js"></script>
				<div class="g-ytsubscribe" data-channelid="<?php echo $block->channel->id; ?>" data-layout="default" data-count="default"></div>
			</div>
		</div>
        <div class="mxyt-channel-descr">
			<div class="mxyt-text-description mxyt-less"><div class="mxyt-text-description-full"><?php echo $block->getFullVideoDescr($block->channel->snippet->description);?></div></div>
		</div>
    </div>
    <div class="mxyt-channel-videos">
    	<div class="mxyt-channel-playlist-chooser">
			<div class="mxyt-playlist-select">
				<?php 
                $list = '<ul>';
                foreach($block->playlists as $plID=>$plTitle){
                    if($plID==$block->getData('playlist_id')){
                        echo '<b>'.$plTitle.' <i class="mxyt-icon mxyt-icon-angle-down" aria-hidden="true"></i></b>';
                    }
                    else{
                        $list.= '<li><span data-mxyt-cfg="'.$block->getAjaxCfg(array('playlist_id'=>$plID)).'">'.$plTitle.'</span></li>';
                    }
                }
                $list.= '</ul>';
                echo $list;
                ?>
			</div>
		</div>
        <div class="mxyt-playlist mxyt-cols-<?php echo $block->getData('responsive_limit');?>">
                <?php
				if($block->getData('cols')>1){
					echo '<div class="mxyt-brow">';
				}
                $i=0;
                $total = count($block->videos);
                foreach($block->videos as $video){
                    $i++;
					if($block->getData('cols')>1){
						echo '<div class="mxyt-bcol-'.$block->getData('cols').'">';
					}
                    ?>
                        <div class="mxyt-playlist-item">
                            <div class="mxyt-video <?php echo ($isVideoSingle?'mxyt-single':'');?>">
                                <?php
                                echo $block->getVideoHTML($video,$block->getData());
                                ?>
                            </div>
                            <?php 
                            if($block->canDisplay('title')){
                                ?>
                                <div class="mxyt-title">
                                    <?php
                                    echo '<h3>'.$video->snippet->title.'</h3>';
                                    ?>
                                </div>
                                <?php
                            }
                            if($block->canDisplay('description')){
                                ?>
                                <div class="mxyt-description">
                                    <div class="mxyt-text-description mxyt-less"><div class="mxyt-text-description-full"><?php echo $block->getFullVideoDescr($video->snippet->description);?></div></div>
                                </div>
                                <?php
                            }
                            if($block->canDisplay('meta')){
                                ?>
                                <div class="mxyt-meta">
                                    <div class="mxyt-views mxyt-tip" title="<?php echo __('Number of views');?>"><i class="mxyt-icon mxyt-icon-views"></i> <?php echo $video->statistics->viewCount;?></div>
                                    <div class="mxyt-likes mxyt-tip" title="<?php echo __('Number of likes');?>"><i class="mxyt-icon mxyt-icon-likes"></i> <?php echo $video->statistics->likeCount;?></div>
                                    <div class="mxyt-dislikes mxyt-tip" title="<?php echo __('Number of dislikes');?>"><i class="mxyt-icon mxyt-icon-dislikes"></i> <?php echo $video->statistics->dislikeCount;?></div>
                                    <div class="mxyt-favs mxyt-tip" title="<?php echo __('Added to favorites');?>"><i class="mxyt-icon mxyt-icon-favs"></i> <?php echo $video->statistics->favoriteCount;?></div>
                                    <div class="mxyt-comments mxyt-tip" title="<?php echo __('Number of comments');?>"><i class="mxyt-icon mxyt-icon-comments"></i> <?php echo $video->statistics->commentCount;?></div>
                                </div>
                                <?php
                            }
                        ?>
                        </div>
                    </div>
                    <?php
                    if($block->getData('cols')>1 && $i%(int)$block->getData('cols')==0 && $i<$total){
                        echo '</div><div class="mxyt-brow">';
                    }
                }
				if($block->getData('cols')>1){
					echo '</div>';
				}
                ?>
        </div>
        
        <?php
        if($block->getData('load_more') && isset($block->playlist->nextPageToken)){
            echo '<div class="mxyt-more"><span class="mxyt-button mxyt-load-more'.($block->getData('infinite_scroll')?' mxyt-infinite-scroll':'').'" data-mxyt-pagetoken="'.$block->playlist->nextPageToken.'" data-mxyt-cfg="'.$block->getAjaxCfg().'">'.$block->getData('load_more_text').'...</span></div>';
        }
        ?>
    </div>
</section>
