<section class="mxYouTubeR mxYouTubeR_video mxYouTubeR_theme_<?php echo $block->getData('theme');?>">
	<div class="mxyt-video">
    	<?php
		echo $block->getVideoHTML($block->video,$block->getData());
		?>
    </div>
    <?php 
	if($block->canDisplay('title') || $block->canDisplay('channel') || $block->canDisplay('date')){
		?>
		<div class="mxyt-title">
			<?php
			if($block->canDisplay('date')) echo '<div class="mxyt-date">'.date($block->getData('date_format'),strtotime($block->video->snippet->publishedAt)).'</div>';
			if($block->canDisplay('title')) echo '<h1>'.$block->video->snippet->title.'</h1>';
			if($block->canDisplay('channel')){
				?>
                <div class="mxyt-channel">
                	<img src="<?php echo $block->channel->snippet->thumbnails->default->url;?>" alt="<?php echo $block->channel->snippet->title;?>">
                    <h3><?php echo $block->channel->snippet->title;?></h3>
                </div>
                <?php
			}
			?>
		</div>
		<?php
	}
	if($block->canDisplay('description')){
		?>
        <div class="mxyt-description">
        	<div class="mxyt-text-description mxyt-less"><div class="mxyt-text-description-full"><?php echo $block->getFullVideoDescr($block->video->snippet->description);?></div></div>
        </div>
		<?php
	}
	if($block->canDisplay('meta')){
		?>
        <div class="mxyt-meta">
        	<div class="mxyt-views mxyt-tip" title="<?php echo __('Number of views');?>"><i class="mxyt-icon mxyt-icon-views"></i> <?php echo $block->video->statistics->viewCount;?></div>
        	<div class="mxyt-likes mxyt-tip" title="<?php echo __('Number of likes');?>"><i class="mxyt-icon mxyt-icon-likes"></i> <?php echo $block->video->statistics->likeCount;?></div>
        	<div class="mxyt-dislikes mxyt-tip" title="<?php echo __('Number of dislikes');?>"><i class="mxyt-icon mxyt-icon-dislikes"></i> <?php echo $block->video->statistics->dislikeCount;?></div>
        	<div class="mxyt-favs mxyt-tip" title="<?php echo __('Added to favorites');?>"><i class="mxyt-icon mxyt-icon-favs"></i> <?php echo $block->video->statistics->favoriteCount;?></div>
        	<div class="mxyt-comments mxyt-tip" title="<?php echo __('Number of comments');?>"><i class="mxyt-icon mxyt-icon-comments"></i> <?php echo $block->video->statistics->commentCount;?></div>
        </div>
		<?php
	}
	?>
</section>
