<?php 
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
	$cartModel = $objectManager->get('\Magento\Checkout\Model\Cart');
	$storepickupHelper 	= $objectManager->get('Magehit\Storepickup\Helper\Data');
	$showpickupdate		= $objectManager->get('\Magento\Framework\App\Config\ScopeConfigInterface')->getValue('carriers/storepickup/showpickupdate', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
	$quote = $cartModel->getQuote();
	if($quote->getId()):
	$shippingMethod = $cartModel->getQuote()->getShippingAddress()->getShippingMethod();
?>
<script>
	window.storepickupData = '<?= /* @escapeNotVerified */ $quote->getStorepickupData() ? json_encode($objectManager->get('Magehit\Storepickup\Serialize\Serializer\Json')->unserialize($quote->getStorepickupData())) : null; ?>';
	window.shippingMethod = '<?= /* @escapeNotVerified */ $shippingMethod ?>';
	window.showpickupdate = Boolean(Number('<?= /* @escapeNotVerified */ $showpickupdate ?>'));
</script>

<?php endif; ?>
<script>
	window.storepickupAvaiable = '<?= /* @escapeNotVerified */ count($storepickupHelper->getDetailsStorePickupAvaiable($quote)) ? json_encode($storepickupHelper->getDetailsStorePickupAvaiable($quote)) : null ;?>';
</script>