
<section class="mxYouTubeR mxYouTubeR_playlist mxYouTubeR_theme_<?php echo $block->getData('theme');?>">
	<div class="mxyt-playlist mxyt-cols-<?php echo $block->getData('responsive_limit');?>">
    	<div class="mxyt-brow">
			<?php
			$i=0;
			$total = count($block->videos);
			foreach($block->videos as $video){
				$i++;
				?>
                <div class="mxyt-bcol-<?php echo $block->getData('cols');?>">
                    <div class="mxyt-playlist-item-blank">
                    	<div class="ch-item">
                            <div class="ch-info">
                                <h3><?php echo $video->snippet->title;?></h3>
                                <a href="<?php echo 'https://www.youtube.com/embed/'.$video->id.'?autoplay=1'.($block->getData('suggested_videos')=='false'?'&rel=0':'');?>" class="mxyt-lightbox" data-rel="<?php echo $block->getData('rel');?>" target="_blank"><span class="mxyt-icon mxyt-icon-play"></span></a>
                            </div>
                            <div class="ch-thumb" style="background-image:url(<?php echo $block->getThumbURL($video,$block->getData('size'));?>);z-index:<?php echo $total+100-$i;?>"></div>
                        </div>
                    </div>
                </div>
                <?php
				if($i%(int)$block->getData('cols')==0 && $i<$total){
					echo '</div><div class="mxyt-brow">';
				}
			}
            ?>
        </div>
    </div>
    
	<?php
    if($block->getData('load_more') && isset($block->playlist->nextPageToken)){
        echo '<div class="mxyt-more"><span class="mxyt-button mxyt-load-more'.($block->getData('infinite_scroll')?' mxyt-infinite-scroll':'').'" data-mxyt-pagetoken="'.$block->playlist->nextPageToken.'" data-mxyt-cfg="'.$block->getAjaxCfg().'">'.$block->getData('load_more_text').'...</span></div>';
    }
    ?>
    
</section>
















