<?php
    $contacts_config = $this->getConfig('porto_settings/contacts');
    $_enable = $contacts_config['enable'];
    if($_enable){
        $_apikey = $contacts_config['api_key'];
        $_full_width = $contacts_config['full_width'];
        $_address = $contacts_config['address'];
        $_zoom = $contacts_config['zoom'];
        $_center_lat = $contacts_config['latitude'];
        $_center_lng = $contacts_config['longitude'];
?>
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?<?php if($_apikey): ?>key=<?php echo $_apikey; ?><?php else: ?>v=3.17<?php endif; ?>"></script>
<script type="text/javascript">
    function initialize() {
        var pos = new google.maps.LatLng(<?php echo $_center_lat; ?>, <?php echo $_center_lng; ?>);
        var mapOptions = {
            center: pos,
            panControl: true,
            zoomControl: true,
            mapTypeControl: true,
            scaleControl: true,
            streetViewControl: true,
            overviewMapControl: true,
            zoom: <?php echo $_zoom; ?>
        };
        var map = new google.maps.Map(document.getElementById("store_map_1"), mapOptions);
        var marker = new google.maps.Marker({
            position: pos,
            map: map,
            title: '<?php echo $_address; ?>'
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>
<?php if(!$_full_width): ?>
<div class="container">
<?php endif; ?>

<h2>Canada Distribution <b>Center</b></h2>
<p class="contact-us">
We start 2020 off with a bang! We are proud to announce that due to our remarkable growth, we are moving to a new location as of January 2020. 
We will continue to offer the same friendly service at our new address on 1579 Kingsway Ave, Port Coquitlam, BC which will allow us to offer an even larger selection of products and services. 
This location is also our main headquarters where we meet new customers, test and inpsect each bike prior to shipping. Our Canadian headquarters is also open for local pickups and test rides during the regular work hours. There is no need of appointment to visit our headquarter.  Our complete address is 1579 Kingsway Ave Unit 1125, Port Coquitlam, BC, V3C 0H1, Canada.
Please click below for <a href="/help-center/article/can-i-pick-up-my-bike-canadian-customers">local pickup instructions.</a>
</p>

<div id="store_map_1" style="min-height: 300px; width: 100%;"></div>
<?php if(!$_full_width): ?>
</div>
<?php endif; ?>
<?php
    }
?>
