<?php 
$block->setData('mode','lightbox');
?>
<section class="mxYouTubeR mxYouTubeR_playlist mxYouTubeR_theme_<?php echo $block->getData('theme');?>">
	<div class="mxyt-playlist mxyt-cols-<?php echo $block->getData('responsive_limit');?>">
    	<div class="mxyt-brow">
			<?php
			$i=0;
			$total = count($block->videos);
			foreach($block->videos as $video){
				$i++;
				$video->contentDetails->duration = null;
				?>
                <div class="mxyt-bcol-<?php echo $block->getData('cols');?>">
                    <div class="mxyt-flipcards-playlist-item">
                        <div class="mxyt-video" style="background-image:url(<?php echo $block->getThumbURL($video,$block->getData('size'));?>);">
                            <?php
                            echo $block->getVideoHTML($video,$block->getData());
                            ?>
                        </div>
                        <div class="mxyt-flipcards-info" style="background-image:url(<?php echo $block->getThumbURL($video,$block->getData('size'));?>);">
                        	<a href="<?php echo 'https://www.youtube.com/embed/'.$video->id.'?autoplay=1'.($block->getData('suggested_videos')=='false'?'&rel=0':'');?>" class="mxyt-flipcards-link mxyt-lightbox" data-rel="mxYouTubeR:flipcards" target="_blank">
                            	<div class="mxyt-flipcards-limit">
                                    <div class="mxyt-flipcards-title">
                                        <?php
                                        if($block->canDisplay('title')) echo '<h3>'.$video->snippet->title.'</h3>';
                                        ?>
                                    </div>
                                    <div class="mxyt-flipcards-description"><?php echo $block->getLimitVideoDescr($video->snippet->description,(int)$block->getData('max_words'));?></div>
                                    <div class="mxyt-flipcards-limit-fade"></div>
                                </div>
                                <div class="mxyt-flipcards-meta">
                                    <div class="mxyt-views" title="<?php echo __('Number of views');?>"><i class="mxyt-icon mxyt-icon-views"></i> <?php echo (int)@$video->statistics->viewCount;?></div>
                                    <div class="mxyt-likes" title="<?php echo __('Number of likes');?>"><i class="mxyt-icon mxyt-icon-likes"></i> <?php echo (int)@$video->statistics->likeCount;?></div>
                                    <div class="mxyt-comments" title="<?php echo __('Number of comments');?>"><i class="mxyt-icon mxyt-icon-comments"></i> <?php echo (int)@$video->statistics->commentCount;?></div>
                                </div>
                            </a>
                    	</div>
                    </div>
                </div>
                <?php
				if($i%(int)$block->getData('cols')==0 && $i<$total){
					echo '</div><div class="mxyt-brow">';
				}
			}
            ?>
        </div>
    </div>
    
    <?php
    if($block->getData('load_more') && isset($block->playlist->nextPageToken)){
        echo '<div class="mxyt-more"><span class="mxyt-button mxyt-load-more'.($block->getData('infinite_scroll')?' mxyt-infinite-scroll':'').'" data-mxyt-pagetoken="'.$block->playlist->nextPageToken.'" data-mxyt-cfg="'.$block->getAjaxCfg().'">'.$block->getData('load_more_text').'...</span></div>';
    }
    ?>
    
</section>
