<?php 
$product = $block->getProduct();
if($product):
    $img =  '/pub/media/catalog/product'.$product->getData('image');
    $imgName = explode('/', $img);
    $imgName = $imgName[count($imgName) - 1];
    $imgName = substr($imgName, 0, strlen($imgName) - 4);
    $alt = !empty($block->getData('alt')) ? $block->getData('alt') : $imgName;
    $width = !empty($block->getData('width')) ? $block->getData('width') : 'auto';
    $height = !empty($block->getData('height')) ? $block->getData('height') : 'auto';
    $title = !empty($block->getData('title')) ? $block->getData('title') : $imgName;;
?>
<img src="<?= $img ?>" alt="<?= $alt ?>" title="<?= $title ?>" style="width: <?= $width; ?>px; height: <?= $height; ?>px"/>
<?php else: ?>
    <?= __('Cannot load product'); ?>
<?php endif; ?>