<?php if($block->isEnable()): ?>
<?php $store = $this->getcurrentStore();
      $_email = $store->getEmail();
 ?>
<style type="text/css">
    .loading-mask{display: none !important;}
    .today{font-weight: bold;}
</style>

<!-- <div class="title-contactstore"><a href="#" class="contactstore"><?= __('Send email to this Ambassador') ?></a></div> -->

<div class="store_detail right">
    <div class="store-info">
        <div class="title-store-info"><?php echo __('Get directions'); ?></div>
        <div class="content-store-info">
        <div>
            <fieldset class="fieldset create info">
                <div class="field field-select-mode">
                    <ul class="vertical">
                            <li mvalue="DRIVING" class="travel car active">DRIVING</li>
                            <li mvalue="TRANSIT" class="travel bus ">TRANSIT</li>
                            <li mvalue="WALKING" class="travel walk">WALKING</li>
                            <li mvalue="BICYCLING" class="travel bicycle">BICYCLING</li>
                    </ul>
                </div>
                <div class="field field-start required">
                    <div class="control">
                    <div class="input-box">
                        <input type="text" class="input-text" id="start" value="" placeholder="Your Location">
                    </div>
                    </div>
                </div>
                <input type="hidden" id="mode" name="mode" value="DRIVING">

                <div class="field field-mode required">
                    <button type="button" title="Get Directions" class="button" id="bntDirection"><span><span>Get Directions</span></span></button>
                    <br/>
                </div>
            </fieldset>
        </div>
        <br/>
        <div id="directions-panel"></div>
        </div>
    </div>

    <div id="map"></div>
    <?php if(trim($block->getContent())):?>
    <div class="store-info store-detail-content" style="margin-top: 20px;">
            <div class="title-store-info"><?php echo __('Description'); ?></div>
            <div class="content-store-info">
            <?php 
               echo $block->getContent();
            ?>
            </div>  
    </div>
    <?php endif;?>
</div>

<div class="store_detail left"> 

<p class="landing-page">
Please note that VoltBike ambassadors are not stores or dealership locations. They are regular customers who own an Voltbike electric bicycle, use it regularly, and are happy to share their experience with others.
</p>

    <div id="street_view" style="margin-bottom:20px;"></div>
    <div class="store-info">
        <div class="title-store-info"><?php echo __('Ambassador details'); ?></div>
        <div class="content-store-info">
            <div class="entry-thumnai">
                <?php
                    if(trim($store->getStore_thumnail()) !=''){
                      $url =   $block->getHelper()->getUrlimage($store->getStore_thumnail());
                    }else{
                       $url = $block->getHelper()->getDefaultimage();
                    }
                ?>
                <img src="<?= $url?>" />
            </div>
            <div class="entry-info">
            <label><?php echo __('Address'); ?></label>
            <div class="entry-item">
                 <?php 

$store_address_full = $store->getStreet();
$pattern = '/\S*\s(.*)/';
echo preg_replace($pattern , "$1", $store_address_full) . '<br>' . 

                //echo $store->getStreet() . '<br>' .
                $store->getCity() . ', ' . $store->getRegion() . ' ' . $store->getPostcode() . '<br>' .
                $store->getCountry(); 
                ?>
            </div>
            <?php if($store->getTelephone()):?>
            <label><?php echo __('Phone'); ?></label>
            <div class="entry-item">
                 <?php 
                 function phone_number_format($number) {
                  // Allow only Digits, remove all other characters.
                  $number2 = preg_replace("/[^\d]/","",$number);
                 
                  // get number length.
                  $length = strlen($number2);
                 
                 // if number = 10
                 if($length == 10) {
                  $number2 = preg_replace("/^1?(\d{3})(\d{3})(\d{4})$/", "$1-$2-$3", $number2);
                  return $number2;
                 }
                  
                  return $number;
                 
                }


                echo phone_number_format($store->getTelephone()); ?>
            </div>
            <?php endif;?>
            <?php if($store->getEmail()):?>
            <label><?php echo __('Email'); ?></label>
            <div class="entry-item">
		<a href="#" class="contactstore"><?= __('Send email to this Ambassador') ?></a>
           <!--      <?php echo $store->getEmail(); ?> -->
            </div>
            <?php endif;?>
            <?php if($store->getFax()):?>
            <label><?php echo __('Fax'); ?></label>
            <div class="entry-item">
                 <?php echo $store->getFax(); ?>
            </div>
            <?php endif;?>
            <?php if($store->getWebsite()):?>
            <label><?php echo __('Website'); ?></label>
            <div class="entry-item">
                <a href="<?php echo $store->getWebsite() ?>" target="_blank"><?php echo $store->getWebsite() ?></a>    
            </div>
            <?php endif;?>
            </div>
            

        </div>
    </div>
    <?php $_products =  explode(",", trim($block->getcurrentStore()->getData('product_ids'),",") );

        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
        
        if($_products):
        $_loop = 'false';
        $_autoplay = 'false';
        if(count($_products) > 4){
            $_loop = 'true';
            $_autoplay = 'true';
        }
        $_catID = trim($block->getHelper()->getConfig('general/cat_id'));
    ?>
    <div class="store-info list-product">
        <div class="title-store-info"><?php echo __('Available Bike(s)'); ?></div>
        <div class="content-store-info">
             <div class="content-store-owl owl-carousel">
        <?php
            foreach ($_products as  $prd):
                $product = $objectManager->create('Magento\Catalog\Model\Product')->load($prd);
         
                if($product->getId() && in_array($_catID,$product->getCategoryIds())):
                $imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
                $image_url = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getThumbnail();         
        ?>
                <div class="item-prd">
                    <a href="<?php echo $product->getProductUrl();?>">
                        <img src="<?php echo $image_url;?>" width="300" />
                        <strong class="product name product-item-name" style="text-align: center;"><?php echo $product->getName();?></strong>
                    </a>
                </div>
                <?php endif;?>
        <?php endforeach;?>
            </div>
       <script type="text/javascript" xml="space">// <![CDATA[
            require([
              'jquery',
              'owl.carousel/owl.carousel.min'
            ], function ($) {
              $(".content-store-owl.owl-carousel").owlCarousel({
                loop: <?= $_loop?>,
                margin: 5,
                autoplay: <?= $_autoplay?>,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                navRewind: true,
                nav: false,
                dots: true,
                responsive: {
                  0: {
                    items:2
                  },
                  768: {
                    items:3
                  },
                  992: {
                    items:3
                  },
                  1200: {
                    items:4
                  }
                }
              });
            });
        // ]]></script>
        </div>
    </div>
    <?php endif;?>
    <?php
    if($store->getStore_schedule() == 1):
        $currentDate = $block->getTimezone()->date();
        $currentDay = strtolower($block->getTimezone()->convertConfigTimeToUtc($currentDate, 'D'));
        $days = [
                'mon'=> __('Monday'),
                'tue'=>__('Tuesday'),
                'wed'=>__('Wednesday'),
                'thu'=>__('Thursday'),
                'fri'=>__('Friday'),
                'sat'=>__('Saturday'),
                'sun'=>__('Sunday')
                ];
        $workTime = unserialize($store->getSchedule());
        if(isset($workTime)):
        ?>
        <div class="store-info store-times">
            <div class="title-store-info"><?php echo __('Opening hours'); ?></div>
            <div class="content-store-info">
                <table class="work-time table">
                <?php foreach ($workTime as $day => $time):?>
                    <?php $string = __('%s'); if($currentDay == $day) $string = __('%s (Today)'); ?>
                    <?php if($time['status']): ?>
                      <tr <?php if($currentDay == $day) echo 'class="today"' ?> >
                        <th class="dayname"><?= sprintf($string,$days[$day])?></th> 
                        <td><?= sprintf(__('%s:%s  -  %s:%s'),$time['from'][0],$time['from'][1],$time['to'][0],$time['to'][1])?></td> 
                      </tr>
                    <?php else:?>
                     <tr <?php if($currentDay == $day) echo 'class="today"' ?> >
                        <th class="dayname"><?= sprintf($string,$days[$day])?></th> 
                        <td><?= __('Close')?></td> 
                      </tr>
                    <?php endif;?>
                    
                <?php endforeach; ?>
                </table>
            </div>
            
        </div>
        <?php endif?>
    <?php endif?>
    
</div>
<div id="contactstore" class="simplePopup" style="display: none;">
<div id="messageresponse"></div>
<div class="page-title" id="pagetitle">
    <h1><?php echo  __('Ambassador Contact') ?></h1>
</div>
<form action="<?php echo $block->getBaseUrl().'storelocator/index/sendmail/' ?>" id="contactForm" method="post">
    <input type="hidden" value="<?php echo  $_email; ?>" name="recipient" id="recipient" />
    <div class="fieldset create info">
        <legend class="legend"><span><?php echo __('Contact Information') ?></span></legend>
       

                <div class="field field-name required">
                    <label class="label" for="name">
                        <span><?php echo  __('Name') ?></span>
                    </label>
                    <div class="control">
                        <input name="name" id="name" title="<?php echo __('Name') ?>" value="<?php echo $block->getCustomerName() ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field field-email required">
                    <label for="email" class="label"><span><?php echo __('Email') ?> </span></label>
                    <div class="control">
                        <input name="store_email" id="store_email" title="<?php echo __('Email') ?>" value="<?php echo $block->getCustomerEmail() ?>" class="input-text required-entry validate-emails" type="text" />
                    </div>
                </div>
                <div class="field field-telephone ">
                    <label class="label" for="telephone"><span><?php echo __('Telephone') ?></span></label>
                    <div class="input-box">
                        <input name="telephone" id="telephone" title="<?php echo __('Telephone') ?>" value="" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field field-comment required">
                    <label for="comment" class="label"><span><?php echo __('Comment') ?></span></label>
                    <div class="input-box">
                        <textarea name="comment" id="comment" title="<?php echo __('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                    </div>
                </div>

    </div>
    <div class="buttons-set">
        <p class="required"><?php echo __('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button id="bntContactsubmit" type="submit"  title="<?php echo  __('Submit') ?>" class="button"><span><span><?php echo __('Submit') ?></span></span></button>
        <img class="img_loader_contact" id="img_loader_contact" src="<?php echo $block->getViewFileUrl('Magehit_Storelocator::images/AjaxLoader.gif'); ?>" alt="" style="display: none;float: left;margin: 10px;width: 15px;">
    </div>
</form>

</div>
<a class="backstore" href="<?php echo $block->getBack(); ?>"><?php echo __('Back to search map') ?></a>

<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
 
   var dataForm = $('#contactForm');
   dataForm.mage('validation', {});
 
});
</script>

<script sync defer type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&key=<?= trim($block->getHelper()->getConfig('map/api_key'))?>">
</script>
<script type="text/javascript">
require([
    "jquery"
], function ($){
    $(document).ready(function(){
        $('.contactstore').click(function(){
            $('#contactstore').simplePopup();
        });
    
        $(document).on('submit','#contactForm',function (event){
            event.preventDefault();
            $('#img_loader_contact').show();
            $.ajax({
                url:'<?php echo $block->getBaseUrl().'storelocator/index/sendmail/' ?>',
                type:'POST',
                showLoader: true,
                dataType:'json',
                data: $( this ).serialize(),                                      
                success:function(transport){
                   
                    var json = transport;
                    var displayString = json.message;
                    if(json.success) {
                        $('#contactForm').hide();
                        $('#img_loader_contact').hide();
                        $('#pagetitle').hide();
                        
                        $('#messageresponse').show();
                        $('#messageresponse').html('<div class="messages success"><div class="success-msg"><span>'+displayString+'</span></div></div>');
                       
                    }
                    else
                    {
                        $('#contactForm').hide();
                        $('#img_loader_contact').hide();
                        $('#pagetitle').hide();
                        
                        $('#messageresponse').show();
                        $('#messageresponse').html('<div class="messages error"><div class="error-msg"><span>'+displayString+'</span></div></div>');
                        
                    }
                },
                error: function(data){
                        $('#contactForm').hide();
                        $('#img_loader_contact').hide();
                        $('#pagetitle').hide();
                        
                        $('#messageresponse').show();
                        $('#messageresponse').html('<div class="messages error"><div class="error-msg"><span>'+'Send email error!'+'</span></div></div>');
                        
                }

            });
        });



    });
    $(document).on('change', '#mode', function(){
       getDirection('<?php echo  $block->escapeHtml($block->getAddress()); ?>');
    });
    $(".vertical li").click(function () {
        $(this).parent().children('li').removeClass('active');
        $(this).addClass('active');
        var tranmode = $(this).attr("mvalue");
        $('#mode').val(tranmode);
        getDirection('<?php echo  $block->escapeHtml($block->getAddress()); ?>');
    });
    $(document).on('click', '#bntDirection', function(){
       getDirection('<?php echo  $block->escapeHtml($block->getAddress()); ?>');
    });

    var center_lat = '<?php echo $block->getCenterLat() ?>';
    var center_lng = '<?php echo $block->getCenterLng() ?>';
    var initial_zoom = <?php echo $block->getInitialZoom() ?>;
    var baseurl = '<?php echo $block->getBaseUrl() ?>';
    var currenturl = '<?php echo $block->getBaseUrl().'storelocator/index/index' ?>';
    var search_result_zoom = <?php echo $block->getSearchResultZoom() ?>;
    var map;
    var markers = [];
    var infoWindow;
    var locationDiv;
    var randomID;
    

    google.maps.event.addDomListener(window, 'load', initialize('<?= $block->getcurrentStore()->getData('lat')?>', '<?= $block->getcurrentStore()->getData('lng')?>', '<?php echo  $block->escapeHtml($block->getAddress()); ?>'));
    
    var directionsDisplay;
    var directionsService = new google.maps.DirectionsService();
    var map;
    var street_view;
    
    function initialize(lat, lng, address) {
        
        directionsDisplay = new google.maps.DirectionsRenderer();
        var storeLatlng = new google.maps.LatLng(lat, lng);
      
        map = new google.maps.Map(document.getElementById("map"), {
            center: storeLatlng,
            zoom: <?php echo  $block->getConfig('map/detail_zoom') ?>,
            mapTypeId: 'roadmap',
            streetViewControl: false,
            mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU}
        });
      
        directionsDisplay.setMap(map);
        directionsDisplay.setPanel(document.getElementById('directions-panel'));
        
        // if (address.length != 0) {
        //     var marker = new google.maps.Marker({
        //     position: storeLatlng,
        //     map: map,
        //     title: address
        //     });
        // }
  
        infoWindow = new google.maps.InfoWindow();

       // locationDiv = document.getElementById("location");
        clearLocations();
        var bounds = new google.maps.LatLngBounds();
        //var searchBox = new google.maps.places.SearchBox(input);
        
        var searchUrl = baseurl+'storelocator/index/search?lat=<?= $block->getcurrentStore()->getData('lat')?>&lng=<?= $block->getcurrentStore()->getData('lng')?>&radius=1000';
        $.ajax({url: searchUrl,
                type: "GET",
                cache: false,
                dataType: "xml",
        }).done(function(xml) {

            //var xml = parseXml(data);
            var markerNodes = xml.documentElement.getElementsByTagName("marker");
            if (markerNodes.length == 0) {
                //document.getElementById("loading_mask_loader").style.display = 'none';
                // document.getElementById("results-slt").style.display = 'none';
                // var address = document.getElementById("address").value;
                alert("There is no store");
                return;
            }
                //document.getElementById("results-slt").style.display = 'block';
                var thum = '';
                //document.getElementById("num-rs").innerHTML = markerNodes.length;
            for (var i = 0; i < markerNodes.length; i++) {
                if(typeof markerNodes[i].getAttribute("thumnail") !== 'undefined'){
                        thum =markerNodes[i].getAttribute("thumnail");
                }
                var id = markerNodes[i].getAttribute("id");
                var name = markerNodes[i].getAttribute("name");
                var url = markerNodes[i].getAttribute("url");
                var address = markerNodes[i].getAttribute("address");
                var phone = markerNodes[i].getAttribute("phone");
                var distance = parseFloat(markerNodes[i].getAttribute("distance"));
                var latlng = new google.maps.LatLng(
                    parseFloat(markerNodes[i].getAttribute("lat")),
                    parseFloat(markerNodes[i].getAttribute("lng")));

                listItem(thum,id, name,url, address,phone, distance, i-1);

                createMarker(latlng, name,thum, address,phone, i,url);
              if(i < 1) {bounds.extend(latlng);}
            }

            map.fitBounds(bounds);
            var zoom = map.getZoom();
            zoom = Math.min(zoom, 12);
            console.log(bounds);
            map.setZoom(zoom);

            //document.getElementById("loading_mask_loader").style.display = 'none';
            // $("#"+randomID).owlCarousel({
            //             autoPlay: 3000, //Set AutoPlay to 3 seconds
            //             items : 3,
            //             navigation : true,
            //             pagination : false,
            //             navigationText : ["<", ">"],
            //         });
        });
        
        var searchBox = new google.maps.places.SearchBox(document.getElementById('start'));
        // var panoramaOptions = {
        //     position: storeLatlng,
        //     pov: {
        //         heading: 34,
        //         pitch: 10
        //     }
        // };
          
        //loadMap();
       var cityCircle = new google.maps.Circle({
            strokeColor: '#909497',
            strokeOpacity: 0.4,
            strokeWeight: 2,
            fillColor: '#FFFFFF',
            fillOpacity: 0.6,
            map: map,
            center: storeLatlng,
            radius: 1000
        });
         
        var panorama = new google.maps.StreetViewPanorama(
            document.getElementById('street_view'), {
              position: {lat: <?= $block->getcurrentStore()->getData('lat')?>, lng: <?= $block->getcurrentStore()->getData('lng')?>},
              pov: {
                heading: 34,
                pitch: 10
              }
            });
         map.setStreetView(panorama);
         document.getElementById('street_view').style.display = 'block';
    }

    function getDirection(destination) {
        var start = document.getElementById('start').value;
        var selectedMode = document.getElementById('mode').value;
    
        var request = {
            origin:start,
            destination:destination,
            travelMode: google.maps.TravelMode[selectedMode],
            unitSystem: <?php echo (($block->getConfig('map/radius_unit') == 'kilometer') ? 'google.maps.UnitSystem.METRIC' : 'google.maps.UnitSystem.IMPERIAL') ?>
        };
        
        directionsService.route(request, function(response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
            }
        });
    }

//add custom 14/12/2018;
 
function clearLocations() {
    infoWindow.close();
    for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(null);
    }
    markers.length = 0;
    // randomID = guRandomid();
    // locationDiv.innerHTML = '<div id="'+randomID+'"></div>';
}
function createMarker(latlng, name,thum, address,phone, num,url) {
   var html = '';
   if(thum == null){
            thum = '<?php echo $block->getViewFileUrl('Magehit_Storelocator::images/store.png'); ?>';
    }
    html += '<div class="store-marker">';
    html += '<div class="address-info"><table><tbody>';
    html += '<tr><td colspan="4" align="left"><h4>'+name+'</h4></td></tr>';
    html += '<tr><td rowspan="3" style="width:60px;"><img width="60" src="'+thum+'"></td></tr>';
    html += '<tr><td><strong>Address:</strong></td><td><p>'+address+'</p></td></tr>';
    if (phone.trim().length > 8) {
      html += '<tr><td><strong>Phone no:</strong></td><td><p>'+phone+'</p></td></tr>';
    }
    html += '<tr><td><strong>  </strong></td><td><a style="display:block;background:#0051B9;color:#FFFFFF;padding:1px 3px" href="'+url+'">Contact this ambassador</a></td></tr>';
    html += '</tbody></table></div>';
    html += '</div>';

    var marker = new google.maps.Marker({
        map: map,
        position: latlng,
        icon: 'http://chart.apis.google.com/chart?chst=d_map_pin_letter_withshadow&chld=' + (num + 1) + '|FF0000|0000FF'  
    });
    google.maps.event.addListener(marker, 'click', function() {
        infoWindow.setContent(html);
        infoWindow.open(map, marker);
    });
    markers.push(marker);
}

function listItem(thum, id, name,url, address,phone, distance, num) {
    num = num + 1;

    element = document.createElement("div");
    if(typeof distance !== 'undefined'){
        var att = document.createAttribute("datamarker");
        att.value = num;
        element.setAttributeNode(att);
        
            // att = document.createAttribute("onmouseout");
            // att.value = "onMouseout(" + num + ")";
            // element.setAttributeNode(att); 
        }
        var att = document.createAttribute('class');
        att.value = "item";
        element.setAttributeNode(att);
        var html = '<div class="inner-item">'; 
        if(thum != null){
            html += '<div class="item-thumb"><img title="" src="'+thum+'"></div>';
        }else{
            html += '<div class="item-thumb"><img title="" src="'+'<?php echo $block->getViewFileUrl('Magehit_Storelocator::images/store.png'); ?>'+'"></div>';
        }
            html += '<div class="item-content"><h3>'+ name + '</h3>';
            // element.innerHTML += '<div class="clear"></div>';
            html += '<div class="address">' + address + '</div>';
            //console.log(phone.trim().length);
            if (phone.trim().length > 8) {
                html += '<h3>'+ '<?= __('Phone Number')?>' + '</h3>';
                html += '<div class="phone-no">'+ phone + '</div>';
            }
                html += '<a class="linkdetailstore" href="'+ url +'">Details and contact with store</a></div></div>';

        html += '</div>';
        element.innerHTML += html;
        
        //document.getElementById(randomID).appendChild(element);
    }

    function downloadUrl(url, callback) {
        var request = window.ActiveXObject ? new ActiveXObject('Microsoft.XMLHTTP') : new XMLHttpRequest;

        request.onreadystatechange = function() {
            if (request.readyState == 4) {
                request.onreadystatechange = doNothing;
                callback(request.responseText, request.status);
            }
        };

        request.open('GET', url, true);
        request.send(null);
    }

    function parseXml(str) {
        if (window.ActiveXObject) {
            var doc = new ActiveXObject('Microsoft.XMLDOM');
            doc.loadXML(str);
            return doc;
        } else if (window.DOMParser) {
            return (new DOMParser).parseFromString(str, 'text/xml');
        }
    }
function guRandomid() {
      function s4() {
        return Math.floor((1 + Math.random()) * 0x10000)
          .toString(16)
          .substring(1);
      }
      return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}
//
});
</script>
<?php
    endif;
?> 
