<style type="text/css">
	.ambassadorsignupform{
		border-top-color: #29363C;
		display: block;
	    border: 1px solid #ececec;
	    border-radius: 8px;
	    background: #fff;
	    border-top: 4px solid #08c;
	    padding: 35px 25px;
	    box-shadow: 0 2px 3px rgba(0,0,0,0.08);
	}
	.ambassadorsignupform label{
		font-weight: 600;
		display: block;
		margin-bottom: 5px;
	}
</style>
<form data-mage-init='{"validation": {}}' action="/storelocator/index/signuppost" class="form ambassadorsignupform" id="ambassadorsignupform-validate" method="post" autocomplete="off">
	<?php
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
	$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	?>
	<input name="in_store" type="hidden" value="<?php echo $storeManager->getStore()->getStoreId();?>">
	<input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<p><?= __('Please signup to join our growing network of VoltBike ambassadors. Once you submit your application, it may take up to 1 day before your contact appears on the ambassador map. 
			Please note that you have to be existing VoltBike owner in order to become ambassador.')?></p>
			<br><br>
		</div>
		<div class="col-lg-6 col-md-6">
			<fieldset class="fieldset create storelocator">
				<div class="field  required">
					<label for="storelocator_first_name" class="label"><span><?= __('First Name')?> </span></label>
					<div class="control">
						<input type="text" name="first_name" id="storelocator_first_name" value="" title="First Name" class="input-text required-entry" data-validate="{required:true}">
					</div>
				</div>
				<div class="field  required">
					<label for="storelocator_last_name" class="label"><span><?= __('Last Name')?> </span></label>
					<div class="control">
						<input type="text" name="last_name" id="storelocator_last_name" value="" title="Last Name" class="input-text required-entry" data-validate="{required:true}">
					</div>
				</div>
				<!-- <input name="store_name" type="hidden" id="storelocator_storename" /> -->
				<div class="field  required">
					<label for="storelocator_email" class="label"><span><?= __('Email')?></span></label>
					<div class="control">
						<input type="text" name="email" id="storelocator_email" value="" title="Email" class="input-text required-entry" data-validate="{required:true, 'validate-email':true}">             
						<p id="note_email"><span>Your email will be used as primary form of communication.</span></p>
					</div>
				</div>
				<div class="field required">
					<label for="storelocator_street" class="label"><span><?=__('Street')?> </span></label>
					<div class="control">
						<input type="text" name="street" id="storelocator_street" value="" title="Street" class="validate-address input-text required-entry" data-validate="{required:true}">                  
						<p id="note_street"><span><a class="linkdetailstore" href="https://www.google.com/maps" target="_blank">Get address from google maps</a></span></p>
					</div>
				</div>
				<div class="field required">
					<label for="storelocator_city" class="label"><span><?=__('City')?></span></label>
					<div class="control">
						<input type="text" name="city" id="storelocator_city" value="" title="City" class="validate-address input-text required-entry" data-validate="{required:true}">                  
					</div>
				</div>
				<div class="field">
					<label for="storelocator_region" class="label"><span><?=__('State/Province')?></span></label>
					<div class="control">
						<input type="text" name="region" id="storelocator_region" value="" title="State/Province" class="validate-address input-text" >                  
					</div>
				</div>
				<div class="field required">
					<label for="storelocator_postcode" class="label"><span><?= __('Zip/Postal Code')?></span> </label>
					<div class="control">
						<input type="text" name="postcode" id="storelocator_postcode" value="" title="Zip/Postal Code " class="input-text required-entry" data-validate="{required:true}">                  
					</div>
				</div>
				<div class="field required">
					<label for="storelocator_country" class="label"><span><?= __('Country') ?></span></label>
					<div class="control">
						<input type="text" name="country" id="storelocator_country" value="" title="Country" class="validate-address input-text required-entry" data-validate="{required:true}">                  
					</div>
				</div>
				<div class="field">
					<label for="storelocator_telephone" class="label"><span><?= __('Phone')?></span></label>
					<div class="control">
						<input type="text" name="telephone" id="storelocator_telephone" value="" title="Telephone" class="input-text" >                  
						<p id="note_email"><span>Entering your phone is optional. Your email will be used as elternative form of communication.</span></p>
					</div>
				</div>
				<div class="field ">
					<label for="storelocator_website" class="label"><span><?= __('Website')?></span></label>
					<div class="control">
						<input type="text" name="website" id="storelocator_website" value="" title="Website" class="input-text">                  
						<p id="note_email"><span>This field is for rental operators or other VoltBike owners who would like to actively promote VoltBike.</span></p>
					</div>
				</div>
				<div class="field  required">
					<input id="storelocator_lat" name="lat" value="" title="Latitude" readonly="" type="hidden" data-validate="{required:true}">	
					<input id="storelocator_lng" name="lng" value="" title="Longitude" readonly="" type="hidden" data-validate="{required:true}">
				</div>
			</fieldset>
		</div>
		<div class="col-lg-6 col-md-6 product_list">
			<input id="products_input" name="products" value=""  type="hidden" />
			<div class="field  required">
				<label for="storelocator_website" class="label"><span><?= __('What is the bike model you own?')?></span></label>
				<div class="control">
				<select id="products" class="select multiselect required-entry" data-validate="{required:true}" size="8"  multiple="multiple">
			<?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('storelocator_products')->toHtml();?>
			<?php
			      
			$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
			$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
			$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
			$categoryId = 11; // YOUR CATEGORY ID
			if($this->getConfig('general/cat_id')){
				$categoryId = $this->getConfig('general/cat_id');
			}
			
			$category = $categoryFactory->create()->load($categoryId);

			$categoryProducts = $category->getProductCollection()
			                             ->addAttributeToSelect('*');

			foreach ($categoryProducts as $product):
			?>
			<option value="<?= $product->getId()?>"><?= $product->getName()?></option>
			<?php endforeach;?>
				</select>		
				</div>

			</div>
			<!-- <div class="field  required">
				<label for="storelocator_website" class="label"><span><?= __('What is the bike model you own?')?></span></label>
				<div class="control">
					<select id="products" class="select multiselect" size="8"  multiple="multiple">
						<option value="63">Voltbike Yukon 750</option>
						<option value="64">Voltbike Yukon 750 Limited</option>
						<option value="67">Voltbike Enduro</option>
						<option value="48">Voltbike Mariner 500w Limited</option>
						<option value="46">Voltbike Elegant</option>
						<option value="23">VoltBike Urban (Black)</option>
						<option value="16">VoltBike Urban (White)</option>					


					</select>
					
				</div>

			</div> -->
		</div>
		<div class="col-lg-12 col-md-12">
		<div class="actions-toolbar">
	        <div class="primary">
	            <button type="submit" class="action submit primary" title="Create an Store"><span>Submit</span></button>
	        </div>
	       
	    </div>
		</div>
	</div>


</form>
<style type="text/css">
.product_list >.field.required>.label:after {
    content: '*';
    color: #e02b27;
    font-size: 1.2rem;
    margin: 0 0 0 4.5px;
}
</style>
<script type="text/x-magento-init">
    {
        "#ambassadorsignupform-validate": {
            "validation": {}
        }
    }
</script>
<script sync defer type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=places&sensor=false&key=<?= trim($block->getHelper()->getConfig('map/api_key'))?>">
</script>          
<script type="text/javascript">
            require([
                'jquery',
                'jquery/ui', 
                'jquery/validate'
            ], function($){ 
            	$( "#products" )
				  .change(function () {
				    var str = "";
				    $( "#products option:selected" ).each(function() {
					    if($(this).val() != 0){

					      str += $(this).val() + ",";
					    }
				    });
				    $( "#products_input" ).val(str);
				  })
				 .change();

            	$('.validate-address').keyup(function(){
                            searchLocation();
                });
                function searchLocation() {
                            var address = document.getElementById("storelocator_street").value + ", "
                            + document.getElementById("storelocator_city").value + ", "
                            + document.getElementById("storelocator_region").value + ", "
                            + document.getElementById("storelocator_country").value;
                
                            var geocoder = new google.maps.Geocoder();
                            geocoder.geocode({address: address}, function(results, status) {
                                if (status == google.maps.GeocoderStatus.OK) {
                                    document.getElementById("storelocator_lat").value = results[0].geometry.location.lat().toFixed(7);
                                    document.getElementById("storelocator_lng").value = results[0].geometry.location.lng().toFixed(7);
                                    
                                } else {
                                     document.getElementById("storelocator_lat").value ='';
                                    document.getElementById("storelocator_lng").value = '';
                                }
                            });
                }
                $.validator.addMethod(
                        'validate-address', function (val) { 
                            console.log($('#itstorelocator_lat').val());
                            if(  $('#storelocator_lat').val() == "" || $('#storelocator_lng').val() == ""){
                                return false;
                            }
                            return true;
                         }, $.mage.__('Please enter a valid address')
                );

            	var dataForm = $('#ambassadorsignupform-validate');
   				dataForm.mage('validation', {});
               

            });//end
</script>

