<form data-mage-init='{"validation": {}}' action="<?php echo $this->getUrl('storelocator/index/uploadphoto') ?>" class="form ambassadorsignupform" id="ambassadorsignupform-photo" method="post" autocomplete="off" enctype="multipart/form-data">
	<?php
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
	$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	?>
	<input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<fieldset class="fieldset create storelocator">
				<div class="field  required">
					<label for="name" class="label"><span><?= __('First & Last Name')?> </span></label>
					<div class="control">
						<input type="text" name="name" id="name" value="" title="<?= __('First & Last Name')?>" class="input-text required-entry" data-validate="{required:true}">
					</div>
				</div>
				<div class="field required">
					<label for="photo" class="label"><span><?=__('Photo')?></span></label>
					<div class="control">
						<input type="file" name="photo" id="photo" value="" title="<?=__('Photo')?>" class="input-text required-entry" data-validate="{required:true}">                  
					</div>
				</div>
				<div class="field required">
					<label for="city" class="label"><span><?=__('City')?></span></label>
					<div class="control">
						<input type="text" name="city" id="city" value="" title="<?=__('City')?>" class="input-text required-entry" data-validate="{required:true}">                  
					</div>
				</div>
				<div class="field required">
					<label for="state" class="label"><span><?=__('State/Province')?></span></label>
					<div class="control">
						<select name="state" id="state" data-validate="{required:true}">
							<?php foreach($this->helper('Magehit\Storelocator\Helper\Data')->getStateByCountry() as $key=>$_state): ?>
							<option value="<?php echo $_state['title'] ?>"><?php echo $_state['label'] ?></option>
							<?php endforeach; ?>
						</select>       						
					</div>
				</div>
				<div class="field">
					<label for="country" class="label"><span><?=__('Country')?></span></label>
					<div class="control">
						<select name="country" id="country">
							<?php foreach($this->helper('Magehit\Storelocator\Helper\Data')->getAllowCountry() as $key=>$_country): ?>
							<option value="<?php echo $key ?>"><?php echo $_country["label"] ?></option>
							<?php endforeach; ?>
						</select>             
					</div>
				</div>
				<div class="field">
					<label for="details" class="label"><span><?= __('Details')?></span></label>
					<div class="control">
						<textarea type="text" name="details" id="details" rows="6"></textarea>                 
					</div>
				</div>
			</fieldset>
		</div>
		
		<div class="col-lg-12 col-md-12">
			<div class="actions-toolbar">
				<div class="primary">
					<button type="submit" class="action submit primary" title="Create an Store"><span>Submit</span></button>
				</div>
			   
			</div>
		</div>
	</div>


</form>
<style type="text/css">
.product_list >.field.required>.label:after {
    content: '*';
    color: #e02b27;
    font-size: 1.2rem;
    margin: 0 0 0 4.5px;
}
</style>
<script type="text/x-magento-init">
    {
        "#ambassadorsignupform-photo": {
            "validation": {}
        }
    }
</script>
         
<script type="text/javascript">
	require([
		'jquery',
		'jquery/ui', 
		'jquery/validate'
	], function($){ 
		$('#country').change(function(){
			var rqUrl = '<?php echo $this->getUrl("storelocator/index/loadstate") ?>';
			$.ajax({
				url : rqUrl + '?country=' + $(this).val(),
				type: 'get',
				showLoader:true,
				dataType: 'json',
				success: function(data){
					$('select#state').html(data.html);
			   }
			});
		});
		

	});//end
</script>

