<?php
/**
 * @var $block \Magehit\Storelocator\Block\Search
 */
?>
<?php
	if($block->isEnable()):
	
	$client_id = '56f48ccc958848ad8d646be4c370612a';
    $client_secret ='dc8c274631414eb49cc706cf4dbecef3';
	$redirect_uri = 'https://www.voltbike.com/community-photos/';
    $code =	'code';
	

	
	$profileUrl = 'https://www.instagram.com/graphql/query/?query_hash=472f257a40c653c64c666ce877d59d2b';
	$iterationUrl = $profileUrl . '&variables={"id":"1167051402","first":50,"after":""}';
	$tryNext = true;
	$limit = 500;
	$found = 0;
	
    $images = array();
	while ($tryNext) {
		$tryNext = false;
		$response = file_get_contents($iterationUrl);
		if ($response === false) {
			break;
		}
		$data = json_decode($response, true);
		if ($data === null) {
			break;
		}
		$media = $data['data']['user']['edge_owner_to_timeline_media'];
		
		foreach ( $media['edges'] as $index => $node ) {
			array_push($images, $node);
        }
		
		$found += count($media['edges']);
		if ($media['page_info']['has_next_page'] && $found < $limit) {
			$iterationUrl = $profileUrl .'&variables={"id":"1167051402","first":50,"after":"'. $media['page_info']['end_cursor'] .'"}';
			$tryNext = true;
		} 
	}
	
	print_r('found  images:' . count($images));
	foreach($images as $img){
		$data = $img['node'];
		echo "<li><a target='_blank' href='https://www.instagram.com/p/". $data['shortcode'] . "'><img src='" .$data['thumbnail_src']. "'/></a></li>";
		print_r($img);die();
	}
?>
<div class="storelocator-search">
    <form id="frm-storelocator-search">
        <content class="content-search-slt">
            <div class="map_container top search-map">
                <div id="map" style="height: 400px"></div>
            </div>
            <p class="loader" id="loading_mask_loader" style="display:none">
                <img src="<?php echo $block->getViewFileUrl('Magehit_Storelocator::images/ajax-loader-tr.gif'); ?>" alt="<?php echo __('Loading...') ?>"/>
                <br/>
                <?php echo __('Please wait...') ?>
            </p>
            <div class="my-instashow"></div>
            
        </content>
    </form>
</div>

<script type="text/javascript">
 require(["jquery","instagramfeed","mageplaza/core/jquery/popup"],function($,instagramfeed){
     $(document).ready(function(){
       $('.open-popup-link').magnificPopup({type:'inline'});
       $('.popup-youtube').magnificPopup({
          disableOn: 700,
          type: 'iframe',
          mainClass: 'mfp-fade',
          removalDelay: 160,
          preloader: false,
          fixedContentPos: false
        });

		setTimeout(function(){
        var locations = "Innisfail, Alberta"; 
        $('.my-instashow').eappsInstagramFeed({
            api: 'instashow/api/index.php',
            source: '#voltbikeurban',
            filterOnly: '@voltbike',
			filter :  function(image) {
				console.log(image);
				//return new RegExp(locations).test(image.location);
			},
			
            width: 'auto',
            layout: 'grid',
            columns: 5,
            rows: 1,
            lang: 'en'
        });

}, 2000);
     })
})
</script>
<script type="text/javascript">

require([
        "jquery"
        ], function ($){

    $('#radius_search').on("change mousemove", function() {
        $('#radius-value .num-range').html($(this).val());
    });
    $('.chose-search-slt').on("change", function() {
        if($(this).val() == 'location'){
            $('.input-radius-slt').show();
            $('.gr-search-slt').show();
            $('.input-attribute-slt').hide();
            $('#product_search').hide();
           
        }else{
            $('.input-radius-slt').hide();
            $('.input-attribute-slt').show();
            $('.gr-search-slt').hide();;
            $('#product_search').show();
            
        }
    });

})
</script>
<script sync defer type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=places&key=<?= trim($block->getHelper()->getConfig('map/api_key'))?>">
</script>

<script type="text/javascript">
require([
        "jquery"
        ], function ($){
           var center_lat = <?php echo $block->getCenterLat() ?>;
           var center_lng = <?php echo $block->getCenterLng() ?>;
           var initial_zoom = <?php echo $block->getInitialZoom() ?>;
           var baseurl = '<?php echo $block->getBaseUrl() ?>';
           var search_result_zoom = <?php echo $block->getSearchResultZoom() ?>;
           var map;
           var markers = [];
           var infoWindow;
           var randomID;

           google.maps.event.addDomListener(window, 'load',  loadMap);
		
		$(window).load( function(){
			$('.chose-search-slt').val('location');
			$('.input-radius-slt').show();
			$('.gr-search-slt').show();
			$('.input-attribute-slt').hide();
			$('#product_search').hide();
		});
		
    $(document).on('mouseover', '.inner-item', function(){
        onMouseover($(this).parent().attr( "datamarker" ));
    });
    $(document).on('mouseout', '.inner-item', function(){
        onMouseover($(this).parent().attr( "datamarker" ));
    });
    $(document).on('click', '.inner-item', function(){

        num =$(this).parent().attr( "datamarker" );

        google.maps.event.trigger(markers[num], 'click');
    });
	
    $(document).on('click', '#getbylocal', function(){
       initMap();
    });
	
    function onMouseover(markerNum) {
        markers[markerNum].setAnimation(google.maps.Animation.BOUNCE);
        setTimeout(function(){ markers[markerNum].setAnimation(null); }, 750);
    }
    
    function onMouseout(markerNum) {
        markers[markerNum].setAnimation(null);
    }
    
    function loadMap() {
        //initMap();

        map = new google.maps.Map(document.getElementById("map"), {
            center: new google.maps.LatLng(center_lat,center_lng),
            zoom: initial_zoom,
            mapTypeId: 'roadmap',
            mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU}
        });     
         infoWindow = new google.maps.InfoWindow();

        input = document.getElementById('address');
        var bounds = new google.maps.LatLngBounds();
        var searchBox = new google.maps.places.SearchBox(input);
        
        var searchUrl = baseurl+'storelocator/index/search?all=1';
        $.ajax({url: searchUrl,
                type: "GET",
                cache: false,
                dataType: "xml",
        }).done(function(xml) {

            //var xml = parseXml(data);
            var markerNodes = xml.documentElement.getElementsByTagName("marker");
            if (markerNodes.length == 0) {
                document.getElementById("loading_mask_loader").style.display = 'none';
                // document.getElementById("my-instashow").style.display = 'none';
                // var address = document.getElementById("address").value;
                alert("There is no store");
                return;
            }
                /* document.getElementById("my-instashow").style.display = 'block'; */
                var thum = '';
            for (var i = 0; i < markerNodes.length; i++) {
                if(typeof markerNodes[i].getAttribute("thumnail") !== 'undefined'){
                        thum =markerNodes[i].getAttribute("thumnail");
                }
                var id = markerNodes[i].getAttribute("id");
                var name = markerNodes[i].getAttribute("name");
                var url = markerNodes[i].getAttribute("url");
                var address = markerNodes[i].getAttribute("address");
                var phone = markerNodes[i].getAttribute("phone");
                var distance = parseFloat(markerNodes[i].getAttribute("distance"));
                var latlng = new google.maps.LatLng(
                    parseFloat(markerNodes[i].getAttribute("lat")),
                    parseFloat(markerNodes[i].getAttribute("lng")));

                createMarker(latlng, name,thum, address,phone, i);
                bounds.extend(latlng);
            }

            map.fitBounds(bounds);
            var zoom = map.getZoom();
            zoom = Math.min(zoom, 12);
            map.setZoom(zoom);

            document.getElementById("loading_mask_loader").style.display = 'none';
        });
    }

    function initMap() {

      // Try HTML5 geolocation.
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
            var geocoder = new google.maps.Geocoder();
            var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

            geocoder.geocode({'latLng': latlng}, function(results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[1]) {
                        document.getElementById('address').value = results[1].formatted_address;
                    } else {
                        alert('No results found');
                    }
                } else {
                    alert('Geocoder failed due to: ' + status);
                }
            }.bind(this));

           // document.getElementById("latitude").value = position.coords.latitude;
//            document.getElementById("longitude").value = position.coords.longitude;
			}.bind(this), function(error) {
			}.bind(this));
				}
			}

			function createMarker(latlng, name,thum, address,phone, num) {
			   var html = '';
			   if(thum == null){
						thum = '<?php echo $block->getViewFileUrl('Magehit_Storelocator::images/store.png'); ?>';
				}
				html += '<div class="store-marker">';
				html += '<div class="address-info"><table><tbody>';
				html += '<tr><td colspan="4" align="left"><h4>'+name+'</h4></td></tr>';
				html += '<tr><td rowspan="3"><img width="60" src="'+thum+'"></td></tr>';
				html += '<tr><td><strong>Address:</strong></td><td><p>'+address+'</p></td></tr>';
				html += '<tr><td><strong>Phone no:</strong></td><td><p>'+phone+'</p></td></tr>';
				html += '</tbody></table></div>';
				html += '</div>';

				var marker = new google.maps.Marker({
					map: map,
					position: latlng,
					icon: 'http://chart.apis.google.com/chart?chst=d_map_pin_letter_withshadow&chld=' + (num + 1) + '|FF0000|0000FF'  
				});
				google.maps.event.addListener(marker, 'click', function() {
					infoWindow.setContent(html);
					infoWindow.open(map, marker);
				});
				markers.push(marker);
			}
});

</script>
<?php
   endif;
?>